import {FONT_TYPE} from '@/constant/NGContant';
import {pixelToRem} from '@/utils/common/pxToRem';

export const FigmaBody = {
  Title_Bold: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: pixelToRem(0),
    fontWeight: 600,
    textDecoration: 'none',
    fontSize: pixelToRem(18),
    paragraph: pixelToRem(0),
    lineHeight: pixelToRem(24),
    case: 'original',
  },
  Title: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: pixelToRem(0),
    fontWeight: 500,
    textDecoration: 'none',
    fontSize: pixelToRem(18),
    paragraph: pixelToRem(0),
    lineHeight: pixelToRem(24),
    case: 'original',
  },
  BodyLage: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: pixelToRem(0),
    fontWeight: 400,
    textDecoration: 'none',
    fontSize: pixelToRem(16),
    paragraph: pixelToRem(0),
    lineHeight: pixelToRem(28),
    case: 'original',
  },
  BodyLageBold: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: pixelToRem(0),
    fontWeight: 600,
    textDecoration: 'none',
    fontSize: pixelToRem(16),
    paragraph: pixelToRem(0),
    lineHeight: pixelToRem(28),
    case: 'original',
  },
  BodyMedium: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: pixelToRem(0),
    fontWeight: 400,
    textDecoration: 'none',
    fontSize: pixelToRem(14),
    paragraph: pixelToRem(0),
    lineHeight: pixelToRem(24),
    case: 'original',
  },
  BodyMediumBold: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: pixelToRem(0),
    fontWeight: 600,
    textDecoration: 'none',
    fontSize: pixelToRem(14),
    paragraph: pixelToRem(0),
    lineHeight: pixelToRem(24),
    case: 'original',
  },
  BodySmall: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: pixelToRem(0),
    fontWeight: 400,
    textDecoration: 'none',
    fontSize: pixelToRem(12),
    paragraph: pixelToRem(0),
    lineHeight: pixelToRem(16),
    case: 'original',
  },
  BodySmallBold: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: pixelToRem(0),
    fontWeight: 500,
    textDecoration: 'none',
    fontSize: pixelToRem(12),
    paragraph: pixelToRem(0),
    lineHeight: pixelToRem(16),
    case: 'original',
  },
  BodySmallLight: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: pixelToRem(0),
    fontWeight: 300,
    textDecoration: 'none',
    fontSize: pixelToRem(12),
    paragraph: pixelToRem(0),
    lineHeight: pixelToRem(16),
    case: 'original',
  },
  BodySmallCaption: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: pixelToRem(0),
    fontWeight: 400,
    textDecoration: 'none',
    fontSize: pixelToRem(11),
    paragraph: pixelToRem(0),
    lineHeight: pixelToRem(20),
    case: 'original',
  },
  BodySmallCaptionBold: {
    fontFamily: FONT_TYPE.POPPINS,
    letterSpacing: pixelToRem(0),
    fontWeight: 600,
    textDecoration: 'none',
    fontSize: pixelToRem(11),
    paragraph: pixelToRem(0),
    lineHeight: pixelToRem(20),
    case: 'original',
  },
};
