import {
  AwAddResourceToDemandPopupFragmentComponent,
  AwAddResourceToDemandPopupFragmentService,
} from './fragments';
import {
  AwConfirmMessageComponent,
  AwConfirmMessageService,
  AwSnackbarComponent,
  AwSnackbarService,
} from './services';
import {
  AdvanceSearchComponent,
  AdvanceSearchDialogComponent,
  AwBadgeComponent,
  AwBreadcrumbComponent,
  AwBreadcrumbService,
  AwCardComponent,
  AwContainerComponent,
  AwFilterComponent,
  AwIncrementComponent,
  AwInputBoxDatalistComponent,
  AwInputBoxDateComponent,
  AwInputBoxEmailComponent,
  AwInputBoxMultipleComponent,
  AwInputBoxRadiosComponent,
  AwInputBoxSelectComponent,
  AwInputBoxTextAreaComponent,
  AwInputBoxTextComponent,
  AwLayoutComponent,
  AwLayoutListComponent,
  AwMultiSelectionBoxComponent,
  AwPageHeaderComponent,
  AwPageSubHeaderComponent,
  AwPaginationComponent,
  AwRichButtonComponent,
  AwSearchBoxComponent,
  AwSliderToggleComponent,
  ComfirmDailogComponent,
  ErrorMessageSnackbarComponent,
  FilterGroupComponent,
  FooterComponent,
  HeaderComponent,
  ImageComponent,
  LoadingIndicatorComponent,
  PageNotFoundComponent,
  RedirectComponent,
  RemoveFileComponent,
  SearchBarComponent,
  SidebarComponent,
} from './components';
import {
  AwDragDropDirective,
  AwTooltipComponent,
  AwTooltipDirective,
  AwTooltipInfoComponent,
  AwTooltipInfoDirective,
} from './directive';
import { IsLoadingModule } from '@service-work/is-loading';
import { DragDropModule } from '@angular/cdk/drag-drop';
import { QuillModule } from 'ngx-quill';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MaterialModule } from '../material';
import { FlexLayoutModule } from '@angular/flex-layout';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FileManagerComponent } from './file-manager';
import { ShowAuthedDirective } from './show-authed.directive';
import { NotificationComponent } from './notification';
import { NgModule } from '@angular/core';
import { CoreModule } from '../core/core.module';
import { WelcomeComponent } from '../layouts/welcome';
import { ChooseFileDialogComponent } from '../setting/_dialog';
import { AwUploadFragmentComponent } from './components/aw-upload-fragment/aw-upload-fragment.component';
import { AwRatingStarComponent } from './components/aw-rating-star/aw-rating-star.component';
import { AwDateFormatPipe, AwDateNoTimeFormatPipe } from './pipes';
import { AwAvatarComponent } from './components/aw-avatar/aw-avatar.component';
import { AwNaIfFalsyPipe } from './pipes/aw-na-if-falsy.pipe';
import { AwProfileComponent } from './components/aw-profile/aw-profile.component';
import { AwNavigationComponent } from './components/aw-navigation/aw-navigation.component';
import { AwHtmlToPlainTextPipe } from './pipes/aw-html-to-plain-text.pipe';
import { AwLayoutReportComponent } from './components/aw-layout-report';
import {
  AwCalendarContentComponent,
  AwFilterCalendarLevelPickerComponent,
} from './components/aw-filter-calendar-level-picker';
import { AwCalendarPickerComponent } from './components/aw-filter-calendar-level-picker/aw-calendar-picker.component';
import { AwDateHeaderComponentComponent } from './components/aw-filter-calendar-level-picker/aw-date-header-component';
import { AwCheckboxComponent } from './components/aw-checkbox/aw-checkbox.component';
import { AwStepComponent } from './components/aw-step';

@NgModule({
  declarations: [
    ShowAuthedDirective,
    WelcomeComponent,
    RedirectComponent,
    NotificationComponent,
    ChooseFileDialogComponent,
    AwSnackbarComponent,
    AwPageHeaderComponent,
    AwPageSubHeaderComponent,
    AwRichButtonComponent,
    AwBadgeComponent,
    AwBreadcrumbComponent,
    AwConfirmMessageComponent,
    AwPaginationComponent,
    AwSearchBoxComponent,
    AwTooltipComponent,
    AwTooltipDirective,
    AwIncrementComponent,
    AwMultiSelectionBoxComponent,
    AwLayoutListComponent,
    AwFilterComponent,
    AwSliderToggleComponent,
    AwCardComponent,
    AwLayoutComponent,
    AwAddResourceToDemandPopupFragmentComponent,
    HeaderComponent,
    FooterComponent,
    SidebarComponent,
    PageNotFoundComponent,
    ComfirmDailogComponent,
    FilterGroupComponent,
    AdvanceSearchDialogComponent,
    AdvanceSearchComponent,
    SearchBarComponent,
    AdvanceSearchDialogComponent,
    ErrorMessageSnackbarComponent,
    LoadingIndicatorComponent,
    ImageComponent,
    RemoveFileComponent,
    FileManagerComponent,
    AwUploadFragmentComponent,
    AwDragDropDirective,
    AwRatingStarComponent,
    AwDateFormatPipe,
    AwDateNoTimeFormatPipe,
    AwTooltipInfoDirective,
    AwTooltipInfoComponent,
    AwAvatarComponent,
    AwNaIfFalsyPipe,
    AwProfileComponent,
    AwNavigationComponent,
    AwHtmlToPlainTextPipe,
    AwLayoutReportComponent,
    AwFilterCalendarLevelPickerComponent,
    AwCalendarContentComponent,
    AwCalendarPickerComponent,
    AwDateHeaderComponentComponent,
    AwCheckboxComponent,
    AwContainerComponent,
    AwStepComponent,
    AwInputBoxTextComponent,
    AwInputBoxMultipleComponent,
    AwInputBoxEmailComponent,
    AwInputBoxSelectComponent,
    AwInputBoxDatalistComponent,
    AwInputBoxDateComponent,
    AwInputBoxTextAreaComponent,
    AwInputBoxRadiosComponent,
  ],
  imports: [
    CommonModule,
    RouterModule,
    FlexLayoutModule,
    MaterialModule,
    FormsModule,
    ReactiveFormsModule,
    QuillModule,
    IsLoadingModule,
    CoreModule,
    DragDropModule,
  ],
  exports: [
    IsLoadingModule,
    AwPageHeaderComponent,
    AwPageSubHeaderComponent,
    AwRichButtonComponent,
    AwBadgeComponent,
    AwBreadcrumbComponent,
    AwConfirmMessageComponent,
    AwPaginationComponent,
    AwSearchBoxComponent,
    AwTooltipDirective,
    AwIncrementComponent,
    AwMultiSelectionBoxComponent,
    AwLayoutListComponent,
    AwFilterComponent,
    AwSliderToggleComponent,
    AwCardComponent,
    AwLayoutComponent,
    AwAddResourceToDemandPopupFragmentComponent,
    HeaderComponent,
    FooterComponent,
    SidebarComponent,
    PageNotFoundComponent,
    ComfirmDailogComponent,
    FilterGroupComponent,
    AdvanceSearchDialogComponent,
    AdvanceSearchComponent,
    SearchBarComponent,
    AdvanceSearchDialogComponent,
    ErrorMessageSnackbarComponent,
    LoadingIndicatorComponent,
    ImageComponent,
    RemoveFileComponent,
    FileManagerComponent,
    AwUploadFragmentComponent,
    AwDragDropDirective,
    AwRatingStarComponent,
    AwDateFormatPipe,
    AwDateNoTimeFormatPipe,
    AwTooltipInfoDirective,
    AwAvatarComponent,
    AwNaIfFalsyPipe,
    AwProfileComponent,
    AwNavigationComponent,
    AwHtmlToPlainTextPipe,
    AwLayoutReportComponent,
    AwFilterCalendarLevelPickerComponent,
    AwCheckboxComponent,
    AwContainerComponent,
    AwStepComponent,
    AwInputBoxTextComponent,
    AwInputBoxMultipleComponent,
    AwInputBoxEmailComponent,
    AwInputBoxSelectComponent,
    AwInputBoxDatalistComponent,
    AwInputBoxDateComponent,
    AwInputBoxTextAreaComponent,
    AwInputBoxRadiosComponent,
  ],
  providers: [
    AwSnackbarService,
    AwBreadcrumbService,
    AwConfirmMessageService,
    AwAddResourceToDemandPopupFragmentService,
    AwDateFormatPipe,
    AwDateNoTimeFormatPipe,
  ],
})
export class SharedModule {}
