server:
  port: ${SIGNATURE_PROFILE_MANAGEMENT_PORT:3003}

spring:
  datasource:
    url: jdbc:mysql://${SIGNATURE_DATABASE_HOST:localhost}:${SIGNATURE_DATABASE_PORT:3306}/${DB_PROFILE_MANAGEMENT:esign_profile_dev}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${SIGNATURE_DATABASE_USERNAME:root}
    password: ${SIGNATURE_DATABASE_PASSWORD:mysql}
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate:
        generate-statistics: true
#Log configuration
logging:
  level:
    root: info
    web: debug
    "[com.zaxxer.hikari.HikariConfig]": debug
    "[com.innovationandtrust.signature.configuration.security]": debug
  file:
    path: ./logs
    name: ${logging.file.path}/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      file-name-pattern: ${logging.file.path}/${spring.application.name}-%d{yyyy-MM-dd}.%i.log

#Service configuration
signature:
  file:
    base-path: ${PROFILE_MANAGEMENT_UPLOAD_FILE_PATH:/apps/signature/profile_management}
    data-unit: MB
    max-upload-size: 20
  profile-front-end:
    front-end-base-url: ${FRONT_END_URL:http://localhost:3000}
    super-admin-url: ${SIGNATURE_SUPER_ADMIN_APP_URL:http://localhost:3001}