export const globalPropertiesIcon = {
  sort: 'sort',
  edit: 'edit',
  delete: 'delete',
  create: 'create',
  setting: 'settings',
  summary: 'summarize',
  add: 'add',
  close: 'close',
  cancel: 'cancel',
  expandMore: 'expand_more',
  replay: 'replay',
  search: 'search',
  arrowDropDown: 'arrow_drop_down',
  arrowDropUp: 'arrow_drop_up',
  chevronLeft: 'chevron_left',
  chevronRight: 'chevron_right',
  personAdd: 'person_add',
  openInNew: 'open_in_new',
  folderOpen: 'folder_open',
  checkCircleOutline: 'check_circle_outline',
  errorOutline: 'error_outline',
  report: 'report',
  draft: 'drafts',
  description: 'description',
  contentCopy: 'content_copy',
  folder:'folder',
  modify: 'launch',
  select: 'check_box',
  visibility: 'visibility'
};
