image: docker:19.03.12
services:
  - docker:19.03.12-dind
  
variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/allwebrms:latest
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - sonarqube-check

docker-build:
  stage: build
  script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $TAG_LATEST .
  - docker push $TAG_LATEST
  only:
  - master

sonarqube-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  stage: sonarqube-check
  variables:
    SONAR_PROJECT_BASE_DIR: "${CI_PROJECT_DIR}"
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    SONAR_TOKEN: "5f29d01e0c4366e9126449a54e919a70cf85cbc3"
    SONAR_HOST_URL: "http://10.2.7.2:9000"
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
  allow_failure: true
  only:
    - merge_requests
    - rc/1.0.0
    - master
