server:
  shutdown: graceful
  port: 8183
  forward-headers-strategy: framework
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
spring:
  config:
    activate:
      on-profile:
      - prod
  jackson:
    serialization:
      indent-output: true
    date-format: dd-MM-yyyy hh:mm a
  data:
    rest:
      base-path: /api/v1
  hateoas:
    use-hal-as-default-json-media-type: false
  #Datasource Configauration
  jpa:    
    database: postgresql
    open-in-view: false
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time-zone: UTC
          batch-size: 20
        format-sql: true
        use-sql: true
        generate-statistics: false
        order-inserts: true
        order-updates: true
        bytecode: 
          use-reflection-optimizer: true
        search: 
          autoregister-listener: false
    database-platform: com.allweb.recruit.config.PostgreSQL10JsonDialect
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}?useLegacyDatetimeCode=true&sslmode=disable
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: rms_pro
      driver-class-name: org.postgresql.Driver
      user name: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      maximum-pool-size: 50
      allow-pool-suspension: true
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 200000
      connection-timeout: 30000
      register-mbeans: true
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        rewriteBatchedStatements: true
        reWriteBatchedInserts: true

  web:
    resources:
      chain:
        enabled: true
        strategy:
          content:
            enabled: true
            paths:
            -  /webjars/swagger-ui/**.*
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.2.7.2:8020/realms/aw_recruitment
          jwk-set-uri: http://10.2.7.2:8020/realms/aw_recruitment/protocol/openid-connect/certs
          public-key-location: classpath*:keycloak-key.pub
  
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
      table-prefix: BATCH_

  elasticsearch:
    rest:
      uris: http://elasticsearch:9200
  sql:
    init:
      platform: com.allweb.recruit.config.PostgreSQL10JsonDialect

springdoc:
  pre-loading-enabled: false
  api-docs:
    enabled: true
    groups:
      enabled: true
    resolve-schema-properties: true
  use-fqn: true  
  show-login-endpoint: false
  show-actuator: true
  writer-with-default-pretty-printer: true
  default-produces-media-type: application/hal+json
  default-consumes-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    filter: true
    display-query-params: true
    # supported-submit-methods: 
    #   - GET
    display-operation-id: true

  group-configs:
  - group: All
    paths-to-match: /api/**
  - group: Candidate
    paths-to-match: /api/v1/candidate/**
  - group: Interview
    paths-to-match: /api/v1/interview/**
  - group: Activity
    paths-to-match: /api/v1/activity/**
  - group: Mail
    paths-to-match: /api/v1/mail/**
  - group: University
    paths-to-match: /api/v1/university/**
  - group: Company
    paths-to-match: /api/v1/company/**
  - group: User
    paths-to-match: /api/v1/user/**
  - group: Reminder
    paths-to-match: /api/v1/reminder/**
  - group: Dashboard
    paths-to-match: /api/v1/dashboard/**
  - group: Group
    paths-to-match: /api/v1/group/**
  - group: Module
    paths-to-match: /api/v1/module/**
  - group: System Configuration
    paths-to-match: /api/v1/systemConfig/**
  - group: Job Description
    paths-to-match: /api/v1/jobDescription/**

application:
  storage:
    alias: storage
    default-volume-name: upload
    volumes:
      - alias: upload
        path: ./upload
        storageObjects:
          - alias: Temporary
            mime: directory
            path: /temp
          - alias: Candidate
            mime: directory
            path: /candidate
          - alias: Company
            mime: directory
            path: /company
          - alias: JobDescription
            mime: directory
            path: /job-description
  firebase:
    serviceAccount: classpath:allwebrms-firebase.json
logging:
  level:
    root: INFO
    '[org.keycloak]': INFO
    '[org.springframework.security]': INFO
    '[org.springframework.security.oauth2.jwt]': INFO
    '[org.springframework.data.support]': INFO
    '[com.allweb.rms.repository]': ERROR
    '[com.allweb.rms.service]': ERROR
    '[com.allweb.rms.core.storage]': ERROR
    '[org.quartz]': ERROR
    '[jdbc.sqlonly]': ERROR
    '[jdbc.sqltiming]': ERROR
    '[jdbc.audit]': ERROR
    '[jdbc.resultset]': ERROR
    '[jdbc.resultsettable]': ERROR
    '[org.ehcache]': ERROR
    '[org.springframework.data.elasticsearch.client.WIRE]': TRACE

