eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.name}-${random.int}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

rms:
  firebase:
    database-url: https://allwebrms.firebaseio.com
    service-account: classpath:allwebrms-firebase.json