#server:
#  shutdown: graceful
#  port: 8182
#  forward-headers-strategy: framework
#  compression:
#    enabled: true
#    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
#    min-response-size: 1024
#  http2:
#    enabled: true
#spring:
#  config:
#    activate:
#      on-profile:
#      - dev
#  jackson:
#    serialization:
#      indent-output: true
#      write-dates-with-zone-id: true
#    deserialization:
#      adjust-dates-to-context-time-zone:  true
#    date-format: dd-MM-yyyy hh:mm a
#  data:
#    rest:
#      base-path: /api/v1
#  hateoas:
#    use-hal-as-default-json-media-type: false
#  #Datasource Configauration
#  jpa:
#    database: postgresql
#    open-in-view: false
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        jdbc:
#          batch-size: 20
#          time_zone: Etc/UTC
#        format-sql: true
#        use-sql: true
#        generate-statistics: true
#        order-inserts: true
#        order-updates: true
#        bytecode:
#          use-reflection-optimizer: false
#        search:
#          autoregister-listener: false
#
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://10.2.7.2:5432/aw_recruitment_v1?useLegacyDatetimeCode=true&logger=Slf4JLogger&profileSQL=true&sslmode=disable
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      pool-name: rms_dev
#      username: postgres
#      password: root
#      maximum-pool-size: 30
#      allow-pool-suspension: true
#      minimum-idle: 5
#      idle-timeout: 30000
#      max-lifetime: 200000
#      connection-timeout: 30000
#      register-mbeans: true
#      auto-commit: false
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        rewriteBatchedStatements: true
#        reWriteBatchedInserts: true
#  quartz:
#    job-store-type: jdbc
#    datasource:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://10.2.7.2:5432/aw_recruitment_scheduler
#      username: postgres
#      password: root
#      hikari:
#        pool-name: rms_schedule_dev
#        maximum-pool-size: 5
#        allow-pool-suspension: true
#        minimum-idle: 1
#        idle-timeout: 30000
#        max-lifetime: 200000
#        auto-commit: true
#        data-source-properties:
#          cachePrepStmts: true
#          prepStmtCacheSize: 250
#          prepStmtCacheSqlLimit: 2048
#          rewriteBatchedStatements: true
#          rewriteBatchedInserts: true
#
#  web:
#    resources:
#      chain:
#        enabled: true
#        strategy:
#          content:
#            enabled: true
#            paths:
#            -  /webjars/swagger-ui/**.*
#  main:
#    allow-bean-definition-overriding: true
#    lazy-initialization: false
#
#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          issuer-uri: http://10.2.7.2:8020/realms/aw_recruitment
#          jwk-set-uri: http://10.2.7.2:8020/realms/aw_recruitment/protocol/openid-connect/certs
#          public-key-location: classpath*:keycloak-key.pub
#  batch:
#    job:
#      enabled: true
#    jdbc:
#      table-prefix: BATCH_
#      initialize-schema: always
#
#  elasticsearch:
#    uris: 10.2.7.2:9201
#    restclient:
#      sniffer:
#        interval: 2m
#
#  sql:
#    init:
#      platform: org.hibernate.dialect.PostgreSQLDialect
#
#springdoc:
#  pre-loading-enabled: false
#  api-docs:
#    enabled: true
#    groups:
#      enabled: true
#    resolve-schema-properties: true
#  use-fqn: true
#  show-login-endpoint: false
#  show-actuator: true
#  writer-with-default-pretty-printer: true
#  default-produces-media-type: application/hal+json
#  default-consumes-media-type: application/json
#  swagger-ui:
#    path: /swagger-ui.html
#    display-request-duration: true
#    groups-order: DESC
#    operationsSorter: method
#    disable-swagger-default-url: true
#    filter: true
#    display-query-params: true
#    # supported-submit-methods:
#    #   - GET
#    display-operation-id: true
#
#  group-configs:
#  - group: All
#    paths-to-match: /api/**
#  - group: Candidate
#    paths-to-match: /api/v1/candidate/**
#  - group: Interview
#    paths-to-match: /api/v1/interview/**
#  - group: Activity
#    paths-to-match: /api/v1/activity/**
#  - group: Mail
#    paths-to-match: /api/v1/mail/**
#  - group: University
#    paths-to-match: /api/v1/university/**
#  - group: Company
#    paths-to-match: /api/v1/company/**
#  - group: User
#    paths-to-match: /api/v1/user/**
#  - group: Group
#    paths-to-match: /api/v1/group/**
#  - group: Module
#    paths-to-match: /api/v1/module/**
#  - group: Reminder
#    paths-to-match: /api/v1/reminder/**
#  - group: Dashboard
#    paths-to-match: /api/v1/dashboard/**
#  - group: System Configuration
#    paths-to-match: /api/v1/systemConfig/**
#  - group: Job Description
#    paths-to-match: /api/v1/jobDescription/**
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
#
#application:
#  storage:
#    alias: storage
#    default-volume-name: upload
#    volumes:
#      - alias: upload
#        path: ./upload
#        storageObjects:
#          - alias: Temporary
#            mime: directory
#            path: /temp
#          - alias: Candidate
#            mime: directory
#            path: /candidate
#          - alias: Company
#            mime: directory
#            path: /company
#          - alias: JobDescription
#            mime: directory
#            path: /job-description
#  firebase:
#    serviceAccount: classpath:allwebrms-firebase.json
#logging:
#  level:
#    root: INFO
#    '[org.keycloak]': INFO
#    '[org.springframework.security]': INFO
#    '[org.springframework.security.oauth2.jwt]': INFO
#    '[org.springframework.data.support]': INFO
#    '[com.allweb.rms.repository]': DEBUG
#    '[com.allweb.rms.service]': DEBUG
#    '[com.allweb.rms.controller]': INFO
#    '[com.allweb.rms.core.storage]': DEBUG
#    '[org.hibernate.stat]': ERROR
#    '[org.hibernate.SQL]': ERROR
#    '[org.hibernate.type.descriptor.sql.BasicBinder]': ERROR
#    '[org.hibernate.type.descriptor.sql]': ERROR
#    '[org.quartz]': ERROR
#    '[com.zaxxer.hikari.HikariConfig]': INFO
#    '[jdbc.sqlonly]': ERROR
#    '[jdbc.sqltiming]': ERROR
#    '[jdbc.audit]': ERROR
#    '[jdbc.resultset]': ERROR
#    '[jdbc.resultsettable]': ERROR
#    '[org.springframework.batch]':  DEBUG
#    '[org.hibernate.cache]': DEBUG
#    '[org.ehcache]': DEBUG
#    '[org.springframework.data.elasticsearch.client.WIRE]': TRACE
