server:
  shutdown: graceful
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    servlet:
      path: /api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: signature-corporate-profile
  cloud:
    openfeign:
      lazy-attributes-resolution: true
  sql:
    init:
      mode: always
  # Datasource configuration
  jpa:
    database: mysql
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch-size: 20
        enable_lazy_load_no_trans: true
        format-sql: true
        use-sql: true
        order-inserts: true
        order-updates: true
        bytecode:
          use-reflection-optimizer: true
        dialect: org.hibernate.dialect.MySQLDialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
        javax:
          cache:
            missing_cache_strategy: create
            persistence:
              sharedCache:
                mode: ENABLE_SELECTIVE
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: ${signature.security.keycloak-base-url}/realms/${signature.security.keycloak-realm}/protocol/openid-connect/authorize
            token-uri: ${signature.security.keycloak-base-url}/realms/${signature.security.keycloak-realm}/protocol/openid-connect/token
        registration:
          signature-corporate-profile:
            provider: keycloak
            client-id: ${SIGNATURE_CORPORATE_PROFILE_CLIENT_ID}
            client-secret: ${SIGNATURE_CORPORATE_PROFILE_CLIENT_SECRET}
            authorization-grant-type: client_credential
            scope: openid
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: ${spring.application.name}
      auto-commit: false
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 200000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        rewriteBatchedStatements: true
        rewriteBatchedInserts: true
management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health

signature:
  security:
    keycloak-realm: ${SIGNATURE_KEYCLOAK_REALM:signature-realm-name}
    keycloak-base-url: ${SIGNATURE_KEYCLOAK_URL:http://keycloak-host-name:8020}

    origins: ${SIGNATURE_ALLOWED_ORIGIN}
  keycloak:
    auth-server-url: ${signature.security.keycloak-base-url}
    realm: ${signature.security.keycloak-realm}
    resource: ${SIGNATURE_CORPORATE_PROFILE_CLIENT_ID}
    secret: ${SIGNATURE_CORPORATE_PROFILE_CLIENT_SECRET}
    technical-user-id: ${SIGNATURE_KEYCLOAK_TECHNICAL_USER_UUID}
  feign-client:
    client-registration-id: signature-corporate-profile
    client-id: ${SIGNATURE_CORPORATE_PROFILE_CLIENT_ID}
    enabled: true
    clients:
      profile-url: ${SIGNATURE_PROFILE_URL}
      project-url: ${SIGNATURE_PROJECT_URL}
    contexts:
      profile-context-path: ${SIGNATURE_PROFILE_CONTEXT_PATH}
      project-context-path: ${SIGNATURE_PROJECT_CONTEXT_PATH}
  swagger:
    info:
      securityKey: corporate-management

springdoc:
  swagger-ui:
    oauth:
      client-id: ${signature.keycloak.resource}
      client-secret: ${signature.keycloak.secret}
      realm: ${signature.keycloak.realm}

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000