stages:
  - build

build-frontend:
  stage: build
  only:
    - tags
  except:
    - branches
  image: node:16.13.0
  before_script:
    - 'ls -lrta'
    - 'export http_proxy="$http_proxy"'
    - 'export https_proxy="$https_proxy"'
  script:
    - yarn --version
    - export VERSION=$(node -p "require('./package.json').version")
    - echo "Version are '$VERSION'"
    - cp .docs/build.sh ./
    - echo "Build app"
    - sh build.sh
    - cd dist/apps/portal/    
    - echo "Compress app"
    - tar -zcvf portal-$VERSION.tar.gz *
    - ls -lrt
    - echo "Send app to nexus cxm-raw"
    - >
      RESULT=$(curl -X "POST" "https://nexus.interne.tessi-techno.fr/service/rest/v1/components?repository=cxm-raw"
      -u "$nexus_login:$nexus_password"
      -H "accept: application/json"
      -H "Content-Type: multipart/form-data"
      -F "raw.directory=$VERSION"
      -F "raw.asset1=@portal-$VERSION.tar.gz"
      -F "raw.asset1.filename=portal-front-$VERSION.tar.gz") 
